// Generates lib/core/icons.dart: a name -> Material Symbols (rounded) map covering every
// icon name used in the app and every icon name the API sends. Keeps icon tree-shaking on.
//   node tool/gen_icons.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cache = process.env.PUB_CACHE || path.join(process.env.LOCALAPPDATA || path.join(process.env.HOME || '', '.pub-cache'), 'Pub', 'Cache');
const hosted = [path.join(cache, 'hosted', 'pub.dev'), path.join(process.env.HOME || '', '.pub-cache', 'hosted', 'pub.dev')].find((p) => fs.existsSync(p));
const pkg = fs.readdirSync(hosted).filter((d) => d.startsWith('material_symbols_icons-')).sort().pop();
const symbols = fs.readFileSync(path.join(hosted, pkg, 'lib', 'symbols.dart'), 'utf8');
const available = new Set([...symbols.matchAll(/static const IconData (\w+)_rounded\s*=/g)].map((m) => m[1]));

const walk = (dir, ext) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
  const p = path.join(dir, e.name);
  if (e.isDirectory()) return e.name === 'node_modules' ? [] : walk(p, ext);
  return ext.some((x) => p.endsWith(x)) ? [p] : [];
});
const files = [...walk(path.join(root, 'lib'), ['.dart']), ...walk(path.join(root, '..', 'backend', 'src'), ['.js'])]
  .filter((f) => !f.endsWith(path.join('core', 'icons.dart')));
const used = new Set();
for (const f of files) {
  for (const m of fs.readFileSync(f, 'utf8').matchAll(/'([a-z][a-z0-9_]{1,40})'/g)) if (available.has(m[1])) used.add(m[1]);
}
const names = [...used].sort();
const out = `// GENERATED by tool/gen_icons.mjs — do not edit by hand. Re-run after adding icons.
import 'package:flutter/widgets.dart';
import 'package:material_symbols_icons/symbols.dart';

const _icons = <String, IconData>{
${names.map((n) => `  '${n}': Symbols.${n}_rounded,`).join('\n')}
};

/// Material Symbols Rounded icon by name (names come from the design and the API).
IconData I(String name) => _icons[name] ?? Symbols.circle_rounded;
`;
fs.writeFileSync(path.join(root, 'lib', 'core', 'icons.dart'), out);
console.log(`icons.dart: ${names.length} icons`);
