const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env'), quiet: true });

const crypto = require('crypto');

const isProd = process.env.NODE_ENV === 'production';

function required(name, devFallback) {
  const v = process.env[name];
  if (v) return v;
  if (isProd) throw new Error(`Missing required environment variable ${name}`);
  return devFallback;
}

// In development we derive stable fallback secrets so the app runs out of the box.
// Production refuses to start without real secrets.
const devSecret = (label) => crypto.createHash('sha256').update(`mindbridge-dev-${label}`).digest('hex');

const env = {
  isProd,
  port: parseInt(process.env.PORT || '4000', 10),
  mongoUri: process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/mindbridge',
  useMemoryDb: process.argv.includes('--memory-db') || process.env.USE_MEMORY_DB === 'true',
  jwtSecret: required('JWT_SECRET', devSecret('jwt')),
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || '12h',
  // 32-byte key, hex encoded, used for AES-256-GCM encryption of sensitive fields (NFR2, NFR4).
  // A 64-hex value is used as-is; any other secret (e.g. one generated by a host) is hashed to 32 bytes.
  dataKey: (() => {
    const v = required('DATA_ENCRYPTION_KEY', devSecret('data'));
    return /^[0-9a-f]{64}$/i.test(v) ? Buffer.from(v, 'hex') : crypto.createHash('sha256').update(v).digest();
  })(),
  corsOrigins: (process.env.CORS_ORIGINS || '*').split(',').map((s) => s.trim()),
  studentEmailDomains: (process.env.STUDENT_EMAIL_DOMAINS || 'my.sliit.lk').split(',').map((s) => s.trim().toLowerCase()),
  staffEmailDomains: (process.env.STAFF_EMAIL_DOMAINS || 'sliit.lk').split(',').map((s) => s.trim().toLowerCase()),
  // Fixed Sri Lanka offset (no daylight saving) — all schedules are in local time (GMT+5:30).
  tzOffsetMinutes: 330,
  // Bridge assistant (Google Gemini). Key from https://aistudio.google.com/apikey
  geminiKey: process.env.GEMINI_API_KEY || '',
  bridgeModel: process.env.BRIDGE_MODEL || 'gemini-flash-latest',
  // Used when the main model is busy (high demand / rate limit).
  bridgeFallbackModel: process.env.BRIDGE_FALLBACK_MODEL || 'gemini-flash-lite-latest',
  smtp: {
    host: process.env.SMTP_HOST || '',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
    from: process.env.SMTP_FROM || 'MindBridge <no-reply@mindbridge.local>',
  },
  // When true the API includes one-time codes in responses so the app can be demoed without email.
  // DEMO_MODE=true allows this on a deployed server too — only for coursework demos, never real users.
  demoMode: process.env.DEMO_MODE === 'true',
  // Load the demo data on first start when the database is empty (useful on a fresh cloud database).
  seedIfEmpty: process.env.SEED_IF_EMPTY === 'true',
  exposeDevOtp: process.env.DEMO_MODE === 'true' || (!isProd && process.env.EXPOSE_DEV_OTP !== 'false'),
  publicBaseUrl: process.env.PUBLIC_BASE_URL || '',
  // File storage (optional). cloudinary://<api_key>:<api_secret>@<cloud_name> from the Cloudinary
  // dashboard. Without it, uploads are kept in MongoDB GridFS.
  cloudinaryUrl: process.env.CLOUDINARY_URL || '',
  cloudinaryFolder: process.env.CLOUDINARY_FOLDER || 'mindbridge',
};

if (env.dataKey.length !== 32) {
  throw new Error('DATA_ENCRYPTION_KEY must be 64 hex characters (32 bytes)');
}

module.exports = env;
